-- ─────────────────────────────────────────────────────────────
-- supabase_schema.sql - Database Schema for AfterExam (v1.2)
-- ─────────────────────────────────────────────────────────────

-- 1. Profiles Table
-- Purpose: Holds user profile information. Automatically populated when a new user signs up.
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique not null,
  display_name text,
  avatar_url text,
  is_moderator boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Future compatibility columns for Profiles table:
-- bio text
-- profile_picture text
-- career_interests text[]
-- education_details jsonb
-- user_preferences jsonb

-- 2. Communities Table
-- Purpose: Stores community categories (e.g. Medical, Biotech, Computing). Supports extensible banners, rules, etc.
create table public.communities (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  description text,
  icon text,
  banner_image text,
  color text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_active boolean default true not null
);

-- Future compatibility columns for Communities table:
-- rules text[]
-- rules_description text
-- statistics jsonb

-- 3. Community Posts Table
-- Purpose: Stores forum discussion threads. Relational link to profiles (author) and communities.
create table public.community_posts (
  id bigint generated by default as identity primary key,
  author_id uuid references public.profiles(id) on delete cascade not null,
  community_id bigint references public.communities(id) on delete cascade not null,
  title text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Future compatibility columns for Community Posts table:
-- slug text
-- edited_at timestamp with time zone
-- is_pinned boolean default false
-- is_locked boolean default false
-- view_count int default 0
-- report_count int default 0

-- 4. Post Reactions Table (Likes/Upvotes)
-- Purpose: Tracks post reactions. Unique constraint ensures one reaction per user per post.
create table public.post_reactions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  post_id bigint references public.community_posts(id) on delete cascade not null,
  reaction_type text default 'upvote' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint unique_user_post_reaction unique (user_id, post_id)
);

-- 5. Post Comments Table (Replies)
-- Purpose: Holds discussion replies linked to posts and profile authors.
create table public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.community_posts(id) on delete cascade not null,
  author_id uuid references public.profiles(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Future compatibility columns for Post Comments table:
-- parent_comment_id bigint references public.post_comments(id) on delete cascade (for nested threads)
-- upvote_count int default 0

-- ─────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ─────────────────────────────────────────────────────────────

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.communities enable row level security;
alter table public.community_posts enable row level security;
alter table public.post_reactions enable row level security;
alter table public.post_comments enable row level security;

-- Profiles Policies
create policy "Profiles are viewable by everyone" on public.profiles
  for select using (true);

create policy "Profiles can be created by trigger function" on public.profiles
  for insert with check (true);

create policy "Users can update their own profile" on public.profiles
  for update using (auth.uid() = id);

-- Communities Policies
create policy "Communities are viewable by everyone" on public.communities
  for select using (true);

-- Note: Insert/Update/Delete operations for communities table are omitted.
-- Only database admins or moderators (via service_role or specific roles) can create/modify communities.

-- Community Posts Policies
create policy "Posts are viewable by everyone" on public.community_posts
  for select using (true);

create policy "Authenticated users can create posts" on public.community_posts
  for insert with check (auth.role() = 'authenticated' and author_id = auth.uid());

create policy "Authors can edit their own posts" on public.community_posts
  for update using (author_id = auth.uid());

create policy "Authors can delete their own posts" on public.community_posts
  for delete using (author_id = auth.uid());

-- Post Reactions Policies
create policy "Reactions are viewable by everyone" on public.post_reactions
  for select using (true);

create policy "Authenticated users can react to posts" on public.post_reactions
  for insert with check (auth.role() = 'authenticated' and user_id = auth.uid());

create policy "Users can remove their own reactions" on public.post_reactions
  for delete using (user_id = auth.uid());

-- Post Comments Policies
create policy "Comments are viewable by everyone" on public.post_comments
  for select using (true);

create policy "Authenticated users can add comments" on public.post_comments
  for insert with check (auth.role() = 'authenticated' and author_id = auth.uid());

create policy "Authors can edit their own comments" on public.post_comments
  for update using (author_id = auth.uid());

create policy "Authors can delete their own comments" on public.post_comments
  for delete using (author_id = auth.uid());

-- ─────────────────────────────────────────────────────────────
-- PROFILE CREATION TRIGGER
-- ─────────────────────────────────────────────────────────────

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name, is_moderator)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', 'user_' || substr(new.id::text, 1, 8)),
    coalesce(new.raw_user_meta_data->>'username', 'User ' || substr(new.id::text, 1, 8)),
    false
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

-- Trigger definition
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ─────────────────────────────────────────────────────────────
-- PERFORMANCE INDEXES
-- ─────────────────────────────────────────────────────────────

-- Indexes on foreign keys to optimize joins
create index community_posts_author_id_idx on public.community_posts (author_id);
create index community_posts_community_id_idx on public.community_posts (community_id);
create index post_reactions_user_id_idx on public.post_reactions (user_id);
create index post_reactions_post_id_idx on public.post_reactions (post_id);
create index post_comments_post_id_idx on public.post_comments (post_id);
create index post_comments_author_id_idx on public.post_comments (author_id);

-- Index on created_at for reverse chronological feed speed
create index community_posts_created_at_idx on public.community_posts (created_at desc);

-- ─────────────────────────────────────────────────────────────
-- STRUCTURAL CONFIG SEED DATA
-- ─────────────────────────────────────────────────────────────

-- Seed Default Communities
insert into public.communities (name, slug, description, icon, color) values
  ('Medical & Allied', 'medical', 'Health sciences, Veterinary, Ayurveda, Nursing, and other medical fields.', '🩺', '#06b6d4'),
  ('Biotech & Applied', 'biotech', 'Biotechnology, Pharmacy, Bioinformatics, and applied biological sciences.', '🔬', '#a855f7'),
  ('Computing & Tech', 'computing', 'Computer applications, Coding, Data Science, and IT careers.', '💻', '#eab308')
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  icon = excluded.icon,
  color = excluded.color;
